// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all procedure arg schemas
import * as RunTermProcedure from "../run_term_procedure";

export type RunTermArgs = __Infer<typeof RunTermProcedure.params>;
export type RunTermResult = __Infer<typeof RunTermProcedure.returnType>;

